# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/xenial64'
  config.vm.network 'private_network', ip: '192.168.33.10'

  config.vm.provision 'shell', inline: <<-SHELL
    sed -i.bak -e "s%http://archive.ubuntu.com/ubuntu%http://ftp.iij.ad.jp/pub/linux/ubuntu/archive%g" /etc/apt/sources.list

    # Tideways
    echo "deb http://s3-eu-west-1.amazonaws.com/qafoo-profiler/packages debian main" > /etc/apt/sources.list.d/tideways.list
    wget -qO - https://s3-eu-west-1.amazonaws.com/qafoo-profiler/packages/EEB5E8F4.gpg | sudo apt-key add -

    # Install packages
    apt-get update
    apt-get install -y \
      apache2 \
      php7.0 php7.0-dev php7.0-xml libapache2-mod-php7.0 tideways-php \
      libssl-dev libsasl2-dev \
      mongodb

    # Workaround for mongodb extension
    mkdir -p /usr/local/openssl/include/openssl/
    ln -s /usr/include/openssl/evp.h /usr/local/openssl/include/openssl/evp.h
    mkdir -p /usr/local/openssl/lib/
    ln -s /usr/lib/x86_64-linux-gnu/libssl.a /usr/local/openssl/lib/libssl.a
    ln -s /usr/lib/x86_64-linux-gnu/libssl.so /usr/local/openssl/lib/

    # Install mongodb extension
    pecl install mongodb
    echo "extension=/usr/lib/php/20151012/mongodb.so" > /etc/php/7.0/mods-available/mongodb.ini
    phpenmod mongodb

    # Enable/Disable Apache modules
    a2dismod mpm_event
    a2enmod mpm_prefork
    a2enmod rewrite
    a2enmod php7.0

    cp /vagrant/configs/apache2/000-default.conf /etc/apache2/sites-available/
    chown -R ubuntu.ubuntu /var/www/html
    service apache2 restart

    # Checkout Xhgui
    git clone https://github.com/perftools/xhgui.git /var/www/xhgui
    chown -R ubuntu.ubuntu /var/www/xhgui
  SHELL

  config.vm.provision 'shell', privileged: false, inline: <<-SHELL
    cp /vagrant/fib.php /var/www/html/
    cp /vagrant/configs/xhgui/config.php /var/www/xhgui/config/
    cd /var/www/xhgui
    php install.php
  SHELL
end
