# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    cd /tmp
    export REDASH_BRANCH=v3.0.0
    export REDASH_VERSION=3.0.0.b3134
    wget https://raw.githubusercontent.com/getredash/redash/$\{REDASH_BRANCH\}/setup/ubuntu/bootstrap.sh
    bash ./bootstrap.sh
  SHELL
end
